# Generated by Django 6.0.3 on 2026-04-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex10', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='people',
            table='ex10_people',
        ),
        migrations.AlterModelTable(
            name='planets',
            table='ex10_planets',
        ),
    ]
