# Generated by Django 6.0.3 on 2026-04-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='edited',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='planets',
            old_name='edited',
            new_name='updated',
        ),
    ]
