# Generated by Django 6.0.3 on 2026-04-01 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex09', '0002_rename_edited_people_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='homeworld',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ex09.planets'),
        ),
    ]
