# Generated by Django 5.2.12 on 2026-04-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0002_tips_downvoters_tips_upvoters'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tips',
            options={'permissions': (('can_vote', 'Can upvote or downvote tips'),)},
        ),
    ]
