# Generated by Django 5.2.12 on 2026-04-02 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0003_alter_tips_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tips',
            options={'permissions': (('can_downvote', 'Can downvote tips'),)},
        ),
    ]
