# Generated by Django 5.2.12 on 2026-04-03 10:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ex', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserFavoriteArticle',
            new_name='UserFavouriteArticle',
        ),
    ]
